### ISSUE TITLE
Migrate doesn't create table based on dir

### ISSUE THREAD

**Issue by mnai01** [raisenational/serverless-dynamodb#33]
Table doesnt appear to be creating on `sls offline start`, I have also tried `serverless dynamodb migrate` but no table created. Is this a problem with `serverless-dynamodb` not supporting the migration object? During testing I do have my amazon/dynamodb-local image running 

```yml
custom:
    serverless-dynamodb:
        start:
            docker: true
            port: 8000
            inMemory: true
            migrate: true
            seed: true
            convertEmptyValues: true
            noStart: true
        migration:
            dir: offline/migrations
```
