### ISSUE TITLE
migration should be possible w/out running local dynamodb

### ISSUE THREAD

**Issue by bitsofinfo** [raisenational/serverless-dynamodb#40]
The following should be teased apart: `migrate` should be possible against a target `host` that is not necessarily started by this plugin. This is currently too highly coupled and does not account for the possibility someone may want to leverage the auto migration feature against a separate local dynamodb instance that is not necessarily managed/started by this plugin.

Config should be more like this:
```
  serverless-dynamodb:
    stages:
      - local
      - dev
      - qa
      - stage
      
    migrate:
      enabled: true
      port: 8000
      host: someOtherLocalDynamodb.local

    start:
      bindPort: 8000
      bindAddress: 127.0.0.1
      docker: false
```
