### ISSUE TITLE
Outdated example in readme

### ISSUE THREAD

**Issue by gas1cent** [raisenational/serverless-dynamodb#45]
Hey there, thanks for maintaining the fork!

I've tried to use it and ran into an issue that can be solved with a small update to the readme. It currently states that the config should look like this:
```yaml
plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  serverless-dynamodb:
    port: 8000
    docker: false
```

But in this case setting `docker` to `true` has no effect at all, and running `sls offline start` thrown an error saying Java is not in the path.

What helped me was modifying the `custom` part to:
```yaml
custom:
  serverless-dynamodb:
    start:
      docker: true
```

With this new configuration everything works perfectly fine.
